version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672"  # Remove host port binding
      - "15672" # Management UI port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  gaia:
    build:
      context: ./gaia
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      chunker:
        condition: service_started
      vector_db:
        condition: service_started
      graph_db:
        condition: service_started
      llm:
        condition: service_started
      prompt:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - ./gaia/data:/app/data

  chunker:
    build:
      context: ./chunker
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  vector_db:
    build:
      context: ./vector_db
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  graph_db:
    build:
      context: ./graph_db
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  prompt:
    build:
      context: ./prompt
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
